import Tkinter as tk
import matplotlib.pyplot as plt

class apl:
    def __init__(self):
        self.window=tk.Tk()
        self.window.title("QAL3 Karta Schew")
        self.window.geometry("800x500")


        #Gaz kalibracyjny
        self.ok=tk.Label(self.window,text="Gaz Kalibracyjny",fg="green")
        self.ok.place(x=150,y=5)
        #SIARKA
        self.oks=tk.Label(self.window,text="Siarka",fg="red")
        self.oks.place(x=0,y=30)
        self.so=tk.Entry(self.window,width=10)
        self.so.place(x=0,y=50)
        #AZOT
        self.okn=tk.Label(self.window,text="Azot",fg="red")
        self.okn.place(x=100,y=30)
        self.no=tk.Entry(self.window,width=10)
        self.no.place(x=100,y=50)
        #CO
        self.okc=tk.Label(self.window,text="CO",fg="red")
        self.okc.place(x=200,y=30)
        self.co=tk.Entry(self.window,width=10)
        self.co.place(x=200,y=50)
        #Pyl
        self.okp=tk.Label(self.window,text="Pyl",fg="red")
        self.okp.place(x=300,y=30)
        self.py=tk.Entry(self.window,width=10)
        self.py.place(x=300,y=50)

        #POMIARY
        self.pl=tk.Label(self.window,text="Pomiary",fg="blue")
        self.pl.place(x=140,y=90)
            #Siara
        self.ps=tk.Label(self.window,text="Siarka",fg="blue")
        self.ps.place(x=10,y=120)
        self.sp1=tk.Entry(self.window,width=10)
        self.sp1.place(x=0,y=140)
        self.sp2=tk.Entry(self.window,width=10)
        self.sp2.place(x=0,y=160)
        self.sp3=tk.Entry(self.window,width=10)
        self.sp3.place(x=0,y=180)
        self.sp4=tk.Entry(self.window,width=10)
        self.sp4.place(x=0,y=200)
        self.sp5=tk.Entry(self.window,width=10)
        self.sp5.place(x=0,y=220)
        self.sp6=tk.Entry(self.window,width=10)
        self.sp6.place(x=0,y=240)
        self.sp7=tk.Entry(self.window,width=10)
        self.sp7.place(x=0,y=260)
        self.sp8=tk.Entry(self.window,width=10)
        self.sp8.place(x=0,y=280)
        self.sp9=tk.Entry(self.window,width=10)
        self.sp9.place(x=0,y=300)
        self.sp10=tk.Entry(self.window,width=10)
        self.sp10.place(x=0,y=320)
        self.sp11=tk.Entry(self.window,width=10)
        self.sp11.place(x=0,y=340)
        self.sp12=tk.Entry(self.window,width=10)
        self.sp12.place(x=0,y=360)
            #Azot
        self.pn=tk.Label(self.window,text="Azot",fg="blue")
        self.pn.place(x=110,y=120)
        self.np1=tk.Entry(self.window,width=10)
        self.np1.place(x=90,y=140)
        self.np2=tk.Entry(self.window,width=10)
        self.np2.place(x=90,y=160)
        self.np3=tk.Entry(self.window,width=10)
        self.np3.place(x=90,y=180)
        self.np4=tk.Entry(self.window,width=10)
        self.np4.place(x=90,y=200)
        self.np5=tk.Entry(self.window,width=10)
        self.np5.place(x=90,y=220)
        self.np6=tk.Entry(self.window,width=10)
        self.np6.place(x=90,y=240)
        self.np7=tk.Entry(self.window,width=10)
        self.np7.place(x=90,y=260)
        self.np8=tk.Entry(self.window,width=10)
        self.np8.place(x=90,y=280)
        self.np9=tk.Entry(self.window,width=10)
        self.np9.place(x=90,y=300)
        self.np10=tk.Entry(self.window,width=10)
        self.np10.place(x=90,y=320)
        self.np11=tk.Entry(self.window,width=10)
        self.np11.place(x=90,y=340)
        self.np12=tk.Entry(self.window,width=10)
        self.np12.place(x=90,y=360)
        #CO
        self.pc=tk.Label(self.window,text="CO",fg="blue")
        self.pc.place(x=200,y=120)
        self.cp1=tk.Entry(self.window,width=10)
        self.cp1.place(x=180,y=140)
        self.cp2=tk.Entry(self.window,width=10)
        self.cp2.place(x=180,y=160)
        self.cp3=tk.Entry(self.window,width=10)
        self.cp3.place(x=180,y=180)
        self.cp4=tk.Entry(self.window,width=10)
        self.cp4.place(x=180,y=200)
        self.cp5=tk.Entry(self.window,width=10)
        self.cp5.place(x=180,y=220)
        self.cp6=tk.Entry(self.window,width=10)
        self.cp6.place(x=180,y=240)
        self.cp7=tk.Entry(self.window,width=10)
        self.cp7.place(x=180,y=260)
        self.cp8=tk.Entry(self.window,width=10)
        self.cp8.place(x=180,y=280)
        self.cp9=tk.Entry(self.window,width=10)
        self.cp9.place(x=180,y=300)
        self.cp10=tk.Entry(self.window,width=10)
        self.cp10.place(x=180,y=320)
        self.cp11=tk.Entry(self.window,width=10)
        self.cp11.place(x=180,y=340)
        self.cp12=tk.Entry(self.window,width=10)
        self.cp12.place(x=180,y=360)
        #Pyl
        self.pp=tk.Label(self.window,text="Pyl",fg="blue")
        self.pp.place(x=290,y=120)
        self.pp1=tk.Entry(self.window,width=10)
        self.pp1.place(x=270,y=140)
        self.pp2=tk.Entry(self.window,width=10)
        self.pp2.place(x=270,y=160)
        self.pp3=tk.Entry(self.window,width=10)
        self.pp3.place(x=270,y=180)
        self.pp4=tk.Entry(self.window,width=10)
        self.pp4.place(x=270,y=200)
        self.pp5=tk.Entry(self.window,width=10)
        self.pp5.place(x=270,y=220)
        self.pp6=tk.Entry(self.window,width=10)
        self.pp6.place(x=270,y=240)
        self.pp7=tk.Entry(self.window,width=10)
        self.pp7.place(x=270,y=260)
        self.pp8=tk.Entry(self.window,width=10)
        self.pp8.place(x=270,y=280)
        self.pp9=tk.Entry(self.window,width=10)
        self.pp9.place(x=270,y=300)
        self.pp10=tk.Entry(self.window,width=10)
        self.pp10.place(x=270,y=320)
        self.pp11=tk.Entry(self.window,width=10)
        self.pp11.place(x=270,y=340)
        self.pp12=tk.Entry(self.window,width=10)
        self.pp12.place(x=270,y=360)

        #SAMS
        self.samsl=tk.Label(self.window,text="SAMS",fg="yellow")
        self.samsl.place(x=160,y=390)
        self.samss=tk.Entry(self.window,width=10)
        self.samss.place(x=0,y=420)
        self.samsn=tk.Entry(self.window,width=10)
        self.samsn.place(x=90,y=420)
        self.samsc=tk.Entry(self.window,width=10)
        self.samsc.place(x=180,y=420)
        self.samsp=tk.Entry(self.window,width=10)
        self.samsp.place(x=270,y=420)
        
        #numeracja
        self.num1=tk.Label(self.window,text="_1_",fg="purple")
        self.num1.place(x=360,y=140)
        self.num2=tk.Label(self.window,text="_2_",fg="purple")
        self.num2.place(x=360,y=160)
        self.num3=tk.Label(self.window,text="_3_",fg="purple")
        self.num3.place(x=360,y=180)
        self.num4=tk.Label(self.window,text="_4_",fg="purple")
        self.num4.place(x=360,y=200)
        self.num5=tk.Label(self.window,text="_5_",fg="purple")
        self.num5.place(x=360,y=220)
        self.num6=tk.Label(self.window,text="_6_",fg="purple")
        self.num6.place(x=360,y=240)
        self.num7=tk.Label(self.window,text="_7_",fg="purple")
        self.num7.place(x=360,y=260)
        self.num8=tk.Label(self.window,text="_8_",fg="purple")
        self.num8.place(x=360,y=280)
        self.num9=tk.Label(self.window,text="_9_",fg="purple")
        self.num9.place(x=360,y=300)
        self.num10=tk.Label(self.window,text="_10_",fg="purple")
        self.num10.place(x=360,y=320)
        self.num11=tk.Label(self.window,text="_11_",fg="purple")
        self.num11.place(x=360,y=340)
        self.num12=tk.Label(self.window,text="_12_",fg="purple")
        self.num12.place(x=360,y=360)


        #przycisk zapis zmian
        self.zapis=tk.Button(self.window,text="ZAPISZ",width=20,command=self.zap)
        self.zapis.place(x=610,y=0)

        #przycisk rysoj wykres
        self.rys=tk.Button(self.window,text="WYKRES",width=20,command=self.rysuj)
        self.rys.place(x=610,y=30)

        #zerowanie pol na grafice
        self.plik=open("/home/debb/Pulpit/qal3/dane","r")
        x=[l.strip() for l in self.plik]
        self.so.insert(0,x[0])
        self.no.insert(0,x[1])
        self.co.insert(0,x[2])
        self.py.insert(0,x[3])
        self.sp1.insert(0,x[4])
        self.sp2.insert(0,x[5])
        self.sp3.insert(0,x[6])
        self.sp4.insert(0,x[7])
        self.sp5.insert(0,x[8])
        self.sp6.insert(0,x[9])
        self.sp7.insert(0,x[10])
        self.sp8.insert(0,x[11])
        self.sp9.insert(0,x[12])
        self.sp10.insert(0,x[13])
        self.sp11.insert(0,x[14])
        self.sp12.insert(0,x[15])
        self.np1.insert(0,x[16])
        self.np2.insert(0,x[17])
        self.np3.insert(0,x[18])
        self.np4.insert(0,x[19])
        self.np5.insert(0,x[20])
        self.np6.insert(0,x[21])
        self.np7.insert(0,x[22])
        self.np8.insert(0,x[23])
        self.np9.insert(0,x[24])
        self.np10.insert(0,x[25])
        self.np11.insert(0,x[26])
        self.np12.insert(0,x[27])
        self.cp1.insert(0,x[28])
        self.cp2.insert(0,x[29])
        self.cp3.insert(0,x[30])
        self.cp4.insert(0,x[31])
        self.cp5.insert(0,x[32])
        self.cp6.insert(0,x[33])
        self.cp7.insert(0,x[34])
        self.cp8.insert(0,x[35])
        self.cp9.insert(0,x[36])
        self.cp10.insert(0,x[37])
        self.cp11.insert(0,x[38])
        self.cp12.insert(0,x[39])
        self.pp1.insert(0,x[40])
        self.pp2.insert(0,x[41])
        self.pp3.insert(0,x[42])
        self.pp4.insert(0,x[43])
        self.pp5.insert(0,x[44])
        self.pp6.insert(0,x[45])
        self.pp7.insert(0,x[46])
        self.pp8.insert(0,x[47])
        self.pp9.insert(0,x[48])
        self.pp10.insert(0,x[49])
        self.pp11.insert(0,x[50])
        self.pp12.insert(0,x[51])
        self.samss.insert(0,x[52])
        self.samsn.insert(0,x[53])
        self.samsc.insert(0,x[54])
        self.samsp.insert(0,x[55])
        self.plik.close()

        #labele dla delty
        self.deltl=tk.Label(self.window,text="DELTY", fg="blue")
        self.deltl.place(x=510,y=90)
        self.deltls=tk.Label(self.window,text="SIARKA", fg="blue")
        self.deltls.place(x=410,y=120)
        self.deltln=tk.Label(self.window,text="AZOT", fg="blue")
        self.deltln.place(x=480,y=120)
        self.deltlc=tk.Label(self.window,text="CO", fg="blue")
        self.deltlc.place(x=550,y=120)
        self.deltlp=tk.Label(self.window,text="PYL", fg="blue")
        self.deltlp.place(x=620,y=120)
        self.deltll=tk.Label(self.window,text="Lp.", fg="blue")
        self.deltll.place(x=360,y=120)
        #siara
        self.dsl1=tk.Label(self.window,fg="brown")
        self.dsl1.place(x=410,y=140)
        self.dsl2=tk.Label(self.window,fg="brown")
        self.dsl2.place(x=410,y=160)
        self.dsl3=tk.Label(self.window,fg="brown")
        self.dsl3.place(x=410,y=180)
        self.dsl4=tk.Label(self.window,fg="brown")
        self.dsl4.place(x=410,y=200)
        self.dsl5=tk.Label(self.window,fg="brown")
        self.dsl5.place(x=410,y=220)
        self.dsl6=tk.Label(self.window,fg="brown")
        self.dsl6.place(x=410,y=240)
        self.dsl7=tk.Label(self.window,fg="brown")
        self.dsl7.place(x=410,y=260)
        self.dsl8=tk.Label(self.window,fg="brown")
        self.dsl8.place(x=410,y=280)
        self.dsl9=tk.Label(self.window,fg="brown")
        self.dsl9.place(x=410,y=300)
        self.dsl10=tk.Label(self.window,fg="brown")
        self.dsl10.place(x=410,y=320)
        self.dsl11=tk.Label(self.window,fg="brown")
        self.dsl11.place(x=410,y=340)
        self.dsl12=tk.Label(self.window,fg="brown")
        self.dsl12.place(x=410,y=360)
        #azot
        self.dnl1=tk.Label(self.window,fg="brown")
        self.dnl1.place(x=480,y=140)
        self.dnl2=tk.Label(self.window,fg="brown")
        self.dnl2.place(x=480,y=160)
        self.dnl3=tk.Label(self.window,fg="brown")
        self.dnl3.place(x=480,y=180)
        self.dnl4=tk.Label(self.window,fg="brown")
        self.dnl4.place(x=480,y=200)
        self.dnl5=tk.Label(self.window,fg="brown")
        self.dnl5.place(x=480,y=220)
        self.dnl6=tk.Label(self.window,fg="brown")
        self.dnl6.place(x=480,y=240)
        self.dnl7=tk.Label(self.window,fg="brown")
        self.dnl7.place(x=480,y=260)
        self.dnl8=tk.Label(self.window,fg="brown")
        self.dnl8.place(x=480,y=280)
        self.dnl9=tk.Label(self.window,fg="brown")
        self.dnl9.place(x=480,y=300)
        self.dnl10=tk.Label(self.window,fg="brown")
        self.dnl10.place(x=480,y=320)
        self.dnl11=tk.Label(self.window,fg="brown")
        self.dnl11.place(x=480,y=340)
        self.dnl12=tk.Label(self.window,fg="brown")
        self.dnl12.place(x=480,y=360)
        #tlenek wegla
        self.dcl1=tk.Label(self.window,fg="brown")
        self.dcl1.place(x=550,y=140)
        self.dcl2=tk.Label(self.window,fg="brown")
        self.dcl2.place(x=550,y=160)
        self.dcl3=tk.Label(self.window,fg="brown")
        self.dcl3.place(x=550,y=180)
        self.dcl4=tk.Label(self.window,fg="brown")
        self.dcl4.place(x=550,y=200)
        self.dcl5=tk.Label(self.window,fg="brown")
        self.dcl5.place(x=550,y=220)
        self.dcl6=tk.Label(self.window,fg="brown")
        self.dcl6.place(x=550,y=240)
        self.dcl7=tk.Label(self.window,fg="brown")
        self.dcl7.place(x=550,y=260)
        self.dcl8=tk.Label(self.window,fg="brown")
        self.dcl8.place(x=550,y=280)
        self.dcl9=tk.Label(self.window,fg="brown")
        self.dcl9.place(x=550,y=300)
        self.dcl10=tk.Label(self.window,fg="brown")
        self.dcl10.place(x=550,y=320)
        self.dcl11=tk.Label(self.window,fg="brown")
        self.dcl11.place(x=550,y=340)
        self.dcl12=tk.Label(self.window,fg="brown")
        self.dcl12.place(x=550,y=360)
        #pyl
        self.dpl1=tk.Label(self.window,fg="brown")
        self.dpl1.place(x=620,y=140)
        self.dpl2=tk.Label(self.window,fg="brown")
        self.dpl2.place(x=620,y=160)
        self.dpl3=tk.Label(self.window,fg="brown")
        self.dpl3.place(x=620,y=180)
        self.dpl4=tk.Label(self.window,fg="brown")
        self.dpl4.place(x=620,y=200)
        self.dpl5=tk.Label(self.window,fg="brown")
        self.dpl5.place(x=620,y=220)
        self.dpl6=tk.Label(self.window,fg="brown")
        self.dpl6.place(x=620,y=240)
        self.dpl7=tk.Label(self.window,fg="brown")
        self.dpl7.place(x=620,y=260)
        self.dpl8=tk.Label(self.window,fg="brown")
        self.dpl8.place(x=620,y=280)
        self.dpl9=tk.Label(self.window,fg="brown")
        self.dpl9.place(x=620,y=300)
        self.dpl10=tk.Label(self.window,fg="brown")
        self.dpl10.place(x=620,y=320)
        self.dpl11=tk.Label(self.window,fg="brown")
        self.dpl11.place(x=620,y=340)
        self.dpl12=tk.Label(self.window,fg="brown")
        self.dpl12.place(x=620,y=360)

        


        self.zap()


      
        

        self.window.mainloop()


    def zap(self):
        print("zapis")
        plicz=open("/home/debb/Pulpit/qal3/dane","w")
        plicz.seek(0)
        plicz.write(self.so.get()+'\n'+self.no.get()+'\n'+self.co.get()+'\n'+self.py.get()+'\n'+self.sp1.get()+'\n'+self.sp2.get()+'\n'+self.sp3.get()+'\n'+self.sp4.get()+'\n'+self.sp5.get()+'\n'+self.sp6.get()+'\n'+self.sp7.get()+'\n'+self.sp8.get()+'\n'+self.sp9.get()+'\n'+self.sp10.get()+'\n'+self.sp11.get()+'\n'+self.sp12.get()+'\n'
        +self.np1.get()+'\n'+self.np2.get()+'\n'+self.np3.get()+'\n'+self.np4.get()+'\n'+self.np5.get()+'\n'+self.np6.get()+'\n'+self.np7.get()+'\n'+self.np8.get()+'\n'+self.np9.get()+'\n'+self.np10.get()+'\n'+self.np11.get()+'\n'+self.np12.get()+'\n'
        +self.cp1.get()+'\n'+self.cp2.get()+'\n'+self.cp3.get()+'\n'+self.cp4.get()+'\n'+self.cp5.get()+'\n'+self.cp6.get()+'\n'+self.cp7.get()+'\n'+self.cp8.get()+'\n'+self.cp9.get()+'\n'+self.cp10.get()+'\n'+self.cp11.get()+'\n'+self.cp12.get()+'\n'
        +self.pp1.get()+'\n'+self.pp2.get()+'\n'+self.pp3.get()+'\n'+self.pp4.get()+'\n'+self.pp5.get()+'\n'+self.pp6.get()+'\n'+self.pp7.get()+'\n'+self.pp8.get()+'\n'+self.pp9.get()+'\n'+self.pp10.get()+'\n'+self.pp11.get()+'\n'+self.pp12.get()+'\n'
        +self.samss.get()+'\n'+self.samsn.get()+'\n'+self.samsc.get()+'\n'+self.samsp.get())
        plicz.close()

        #nadpisanie nowo zapisanymi

        plik=open("/home/debb/Pulpit/qal3/dane","r")
        x=[l.strip() for l in plik]
        self.so.delete(0,100)
        self.so.insert(0,x[0])
        self.no.delete(0,100)
        self.no.insert(0,x[1])
        self.co.delete(0,100)
        self.co.insert(0,x[2])
        self.py.delete(0,100)
        self.py.insert(0,x[3])
        self.sp1.delete(0,100)
        self.sp1.insert(0,x[4])
        self.sp2.delete(0,100)
        self.sp2.insert(0,x[5])
        self.sp3.delete(0,100)
        self.sp3.insert(0,x[6])
        self.sp4.delete(0,100)
        self.sp4.insert(0,x[7])
        self.sp5.delete(0,100)
        self.sp5.insert(0,x[8])
        self.sp6.delete(0,100)
        self.sp6.insert(0,x[9])
        self.sp7.delete(0,100)
        self.sp7.insert(0,x[10])
        self.sp8.delete(0,100)
        self.sp8.insert(0,x[11])
        self.sp9.delete(0,100)
        self.sp9.insert(0,x[12])
        self.sp10.delete(0,100)
        self.sp10.insert(0,x[13])
        self.sp11.delete(0,100)
        self.sp11.insert(0,x[14])
        self.sp12.delete(0,100)
        self.sp12.insert(0,x[15])
        self.np1.delete(0,100)
        self.np1.insert(0,x[16])
        self.np2.delete(0,100)
        self.np2.insert(0,x[17])
        self.np3.delete(0,100)
        self.np3.insert(0,x[18])
        self.np4.delete(0,100)
        self.np4.insert(0,x[19])
        self.np5.delete(0,100)
        self.np5.insert(0,x[20])
        self.np6.delete(0,100)
        self.np6.insert(0,x[21])
        self.np7.delete(0,100)
        self.np7.insert(0,x[22])
        self.np8.delete(0,100)
        self.np8.insert(0,x[23])
        self.np9.delete(0,100)
        self.np9.insert(0,x[24])
        self.np10.delete(0,100)
        self.np10.insert(0,x[25])
        self.np11.delete(0,100)
        self.np11.insert(0,x[26])
        self.np12.delete(0,100)
        self.np12.insert(0,x[27])
        self.cp1.delete(0,100)
        self.cp1.insert(0,x[28])
        self.cp2.delete(0,100)
        self.cp2.insert(0,x[29])
        self.cp3.delete(0,100)
        self.cp3.insert(0,x[30])
        self.cp4.delete(0,100)
        self.cp4.insert(0,x[31])
        self.cp5.delete(0,100)
        self.cp5.insert(0,x[32])
        self.cp6.delete(0,100)
        self.cp6.insert(0,x[33])
        self.cp7.delete(0,100)
        self.cp7.insert(0,x[34])
        self.cp8.delete(0,100)
        self.cp8.insert(0,x[35])
        self.cp9.delete(0,100)
        self.cp9.insert(0,x[36])
        self.cp10.delete(0,100)
        self.cp10.insert(0,x[37])
        self.cp11.delete(0,100)
        self.cp11.insert(0,x[38])
        self.cp12.delete(0,100)
        self.cp12.insert(0,x[39])
        self.pp1.delete(0,100)
        self.pp1.insert(0,x[40])
        self.pp2.delete(0,100)
        self.pp2.insert(0,x[41])
        self.pp3.delete(0,100)
        self.pp3.insert(0,x[42])
        self.pp4.delete(0,100)
        self.pp4.insert(0,x[43])
        self.pp5.delete(0,100)
        self.pp5.insert(0,x[44])
        self.pp6.delete(0,100)
        self.pp6.insert(0,x[45])
        self.pp7.delete(0,100)
        self.pp7.insert(0,x[46])
        self.pp8.delete(0,100)
        self.pp8.insert(0,x[47])
        self.pp9.delete(0,100)
        self.pp9.insert(0,x[48])
        self.pp10.delete(0,100)
        self.pp10.insert(0,x[49])
        self.pp11.delete(0,100)
        self.pp11.insert(0,x[50])
        self.pp12.delete(0,100)
        self.pp12.insert(0,x[51])
        self.samss.delete(0,100)
        self.samss.insert(0,x[52])
        self.samsn.delete(0,100)
        self.samsn.insert(0,x[53])
        self.samsc.delete(0,100)
        self.samsc.insert(0,x[54])
        self.samsp.delete(0,100)
        self.samsp.insert(0,x[55])
        self.plik.close()
        #przeliczenie delt w funkcji
        self.dsl1.config(text=self.delta(self.sp1.get(),self.so.get()))
        self.dsl2.config(text=self.delta(self.sp2.get(),self.so.get()))
        self.dsl3.config(text=self.delta(self.sp3.get(),self.so.get()))
        self.dsl4.config(text=self.delta(self.sp4.get(),self.so.get()))
        self.dsl5.config(text=self.delta(self.sp5.get(),self.so.get()))
        self.dsl6.config(text=self.delta(self.sp6.get(),self.so.get()))
        self.dsl7.config(text=self.delta(self.sp7.get(),self.so.get()))
        self.dsl8.config(text=self.delta(self.sp8.get(),self.so.get()))
        self.dsl9.config(text=self.delta(self.sp9.get(),self.so.get()))
        self.dsl10.config(text=self.delta(self.sp10.get(),self.so.get()))
        self.dsl11.config(text=self.delta(self.sp11.get(),self.so.get()))
        self.dsl12.config(text=self.delta(self.sp12.get(),self.so.get()))
        self.dnl1.config(text=self.delta(self.np1.get(),self.no.get()))
        self.dnl2.config(text=self.delta(self.np2.get(),self.no.get()))
        self.dnl3.config(text=self.delta(self.np3.get(),self.no.get()))
        self.dnl4.config(text=self.delta(self.np4.get(),self.no.get()))
        self.dnl5.config(text=self.delta(self.np5.get(),self.no.get()))
        self.dnl6.config(text=self.delta(self.np6.get(),self.no.get()))
        self.dnl7.config(text=self.delta(self.np7.get(),self.no.get()))
        self.dnl8.config(text=self.delta(self.np8.get(),self.no.get()))
        self.dnl9.config(text=self.delta(self.np9.get(),self.no.get()))
        self.dnl10.config(text=self.delta(self.np10.get(),self.no.get()))
        self.dnl11.config(text=self.delta(self.np11.get(),self.no.get()))
        self.dnl12.config(text=self.delta(self.np12.get(),self.no.get()))
        self.dcl1.config(text=self.delta(self.cp1.get(),self.co.get()))
        self.dcl2.config(text=self.delta(self.cp2.get(),self.co.get()))
        self.dcl3.config(text=self.delta(self.cp3.get(),self.co.get()))
        self.dcl4.config(text=self.delta(self.cp4.get(),self.co.get()))
        self.dcl5.config(text=self.delta(self.cp5.get(),self.co.get()))
        self.dcl6.config(text=self.delta(self.cp6.get(),self.co.get()))
        self.dcl7.config(text=self.delta(self.cp7.get(),self.co.get()))
        self.dcl8.config(text=self.delta(self.cp8.get(),self.co.get()))
        self.dcl9.config(text=self.delta(self.cp9.get(),self.co.get()))
        self.dcl10.config(text=self.delta(self.cp10.get(),self.co.get()))
        self.dcl11.config(text=self.delta(self.cp11.get(),self.co.get()))
        self.dcl12.config(text=self.delta(self.cp12.get(),self.co.get()))
        self.dpl1.config(text=self.delta(self.pp1.get(),self.py.get()))
        self.dpl2.config(text=self.delta(self.pp2.get(),self.py.get()))
        self.dpl3.config(text=self.delta(self.pp3.get(),self.py.get()))
        self.dpl4.config(text=self.delta(self.pp4.get(),self.py.get()))
        self.dpl5.config(text=self.delta(self.pp5.get(),self.py.get()))
        self.dpl6.config(text=self.delta(self.pp6.get(),self.py.get()))
        self.dpl7.config(text=self.delta(self.pp7.get(),self.py.get()))
        self.dpl8.config(text=self.delta(self.pp8.get(),self.py.get()))
        self.dpl9.config(text=self.delta(self.pp9.get(),self.py.get()))
        self.dpl10.config(text=self.delta(self.pp10.get(),self.py.get()))
        self.dpl11.config(text=self.delta(self.pp11.get(),self.py.get()))
        self.dpl12.config(text=self.delta(self.pp12.get(),self.py.get()))

    def delta(self,x,y):
        a=float(x)
        b=float(y)
        return round(a-b,3)

    def rysuj(self):
        print("wykres")
        a=round(float(self.so.get())+float(self.samss.get()),3)
        aa=round(float(self.so.get())-float(self.samss.get()),3)
        c=round(float(self.co.get())+float(self.samsc.get()),3)
        cc=round(float(self.co.get())-float(self.samsc.get()),3)
        b=round(float(self.no.get())+float(self.samsn.get()),3)
        bb=round(float(self.no.get())-float(self.samsn.get()),3)
        d=round(float(self.py.get())+float(self.samsp.get()),3)
        dd=round(float(self.py.get())-float(self.samsp.get()),3)
        plt.figure("SIARKA")
        plt.plot([self.sp1.get(),self.sp2.get(),self.sp3.get(),self.sp4.get(),self.sp5.get(),self.sp6.get(),self.sp7.get(),self.sp8.get(),self.sp9.get(),self.sp10.get(),self.sp11.get(),self.sp12.get()],'bo',[a,a,a,a,a,a,a,a,a,a,a,a],'r',[aa,aa,aa,aa,aa,aa,aa,aa,aa,aa,aa,aa],'r')
        plt.ylabel("SIARKA")
        plt.figure("AZOT")
        plt.plot([self.np1.get(),self.np2.get(),self.np3.get(),self.np4.get(),self.np5.get(),self.np6.get(),self.np7.get(),self.np8.get(),self.np9.get(),self.np10.get(),self.np11.get(),self.np12.get()],'bo',[b,b,b,b,b,b,b,b,b,b,b,b],'r',[bb,bb,bb,bb,bb,bb,bb,bb,bb,bb,bb,bb],'r')
        plt.ylabel("AZOT")
        plt.figure("TLENKI WEGLA")
        plt.plot([self.cp1.get(),self.cp2.get(),self.cp3.get(),self.cp4.get(),self.cp5.get(),self.cp6.get(),self.cp7.get(),self.cp8.get(),self.cp9.get(),self.cp10.get(),self.cp11.get(),self.cp12.get()],'bo',[c,c,c,c,c,c,c,c,c,c,c,c],'r',[cc,cc,cc,cc,cc,cc,cc,cc,cc,cc,cc,cc],'r')
        plt.ylabel("TLENKI WEGLA")
        plt.figure("PYL")
        plt.plot([self.pp1.get(),self.pp2.get(),self.pp3.get(),self.pp4.get(),self.pp5.get(),self.pp6.get(),self.pp7.get(),self.pp8.get(),self.pp9.get(),self.pp10.get(),self.pp11.get(),self.pp12.get()],'bo',[d,d,d,d,d,d,d,d,d,d,d,d],'r',[dd,dd,dd,dd,dd,dd,dd,dd,dd,dd,dd,dd],'r')
        plt.ylabel("PYL")
        plt.show()
        
    
        

aplic=apl()


